services:
  - type: web
    name: mealmate
    env: python
    rootDir: delicacies
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn delicacies.delicacies.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: delicacies.delicacies.settings
      - key: PYTHON_VERSION
        value: 3.12.1
