# Generated by Django 5.2.2 on 2025-06-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pieces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper'), ('snack', 'Snack')], max_length=20)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('allergies', models.ManyToManyField(blank=True, to='base.allergy')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitaamins', models.CharField(max_length=100)),
                ('carbohydrates', models.CharField(max_length=100)),
                ('proteins', models.CharField(max_length=100)),
                ('iron', models.CharField(max_length=100)),
                ('calcium', models.CharField(max_length=100)),
                ('fats', models.CharField(max_length=100)),
                ('fiber', models.CharField(max_length=100)),
                ('cholesterol', models.CharField(max_length=100)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mealstation')),
            ],
        ),
    ]
