# Generated by Django 5.2.2 on 2025-06-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrientcorner',
            old_name='vitaamins',
            new_name='vitamins',
        ),
    ]
