# Generated by Django 5.2.2 on 2025-06-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('appetizer', 'Appetizer'), ('salad', 'Salad'), ('other', 'Other')], max_length=20),
        ),
    ]
