# Generated by Django 5.2.2 on 2025-06-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_vitaamins_nutrientcorner_vitamins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealStation',
            new_name='Recipe',
        ),
    ]
