# Generated by Django 5.2.2 on 2025-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='management_of_allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
