# Generated by Django 5.2.2 on 2025-06-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_mealstation_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop',
        ),
    ]
