# Generated by Django 5.2.1 on 2025-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_recipe_management_of_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('appetizer', 'Appetizer'), ('salad', 'Salad'), ('drink', 'drink')], max_length=20),
        ),
    ]
